### ISSUE TITLE
Namespace Help

### ISSUE THREAD

**Issue by pgierz** [willkg/everett#113]
Hello,

Great project! I've been hacking together something similar by hand for most of my tools, but having this as a library is really really nice.

Sorry for a "help wanted" issue, but I'm having a bit of trouble understanding how to setup up namespaces in the configuration. I have a project containing a `config.py`, which has this:

```python
class AppConfig(RequiredConfigMixin):
    """Contains the defaults for the awiesm_bc configuration"""

    config = ConfigOptions()
    config.add_option(
        "debug", parser=bool, default="false", doc="Switch debug mode on and off."
    )
    config.add_option(
        "fc",
        default="gfortran",
        doc="Which ``FORTRAN`` compiler to use for the ``foo`` program",
        namespace="foo",
        parser=str,
    )


def get_config(config_file=None):
    """Loads the configuration

    Loads either the user supplied configuration, the configuration in the XDG
    path, or the default config. Configuration may be given incompletely, so if
    you only supply the color (for example), other configuration values are
    taken from the defaults. The user can also supply a configuration stored in
    a yaml file as an argument to this function, this takes first priority.

    Parameters
    ----------
    config_file : str or Path
        Which config to load

    Returns
    -------
    config : dict (???)
        The configuration to use

    """

    environments = [
        # Look in OS process environment first
        ConfigOSEnv(),
        # Look in YAML files in order specified (CONFIG_FILES is a list)
        ConfigYamlEnv(CONFIG_FILES),
    ]
    if config_file:
        # Add the user supplied configuration file to the front of the list if
        # it was given:
        environments.insert(0, ConfigYamlEnv(config_file))
    manager = ConfigManager(
        # Specify one or more configuration environments in
        # the order they should be checked
        environments=environments,
    )

    # Apply the configuration class to the configuration manager
    # so that it handles option properties like defaults, parsers,
    # documentation, and so on.
    return manager.with_options(AppConfig())
```

In another file, I want to use this `get_config ` function to load specific things I might need to compile a program `foo`, e.g. which compiler the user wants, which libraries, etc etc. That looks like this:

```python
def compile_jsbach_init_file(config=get_config()):
    """Compiles the jsbach init file program"""
    command_to_run = f"{config('fc')} lala.f90"
    # Manual test if errors pop up correctly:
    # command_to_run = "lalala exit 3"
    logger.info("--> Compiling pre-requisite program: jsbach_init_file.f90")
    logger.debug(command_to_run)
    try:
        subprocess.check_output(command_to_run, shell=True)
    except subprocess.CalledProcessError as e:
        error_message = e.output.decode()
        logger.error("ERROR! Sorry...")
        if error_message:
            logger.error(f"{error_message}")
        return e.returncode
    else:
        logger.success("...done!")
        return 0
```

However, I get this error, and I don't understand why or how to fix it. Any help would be great!
```

Traceback (most recent call last):
  File "/Users/pgierz/anaconda3/envs/nml_diff_dev/lib/python3.7/site-packages/everett/manager.py", line 628, in __call__
    option = self.options[key]
  File "/Users/pgierz/anaconda3/envs/nml_diff_dev/lib/python3.7/site-packages/everett/component.py", line 78, in __getitem__
    return self.options.__getitem__(key)
KeyError: 'fc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fortran_progs.py", line 33, in <module>
    compile_jsbach_init_file()
  File "/Users/pgierz/anaconda3/envs/nml_diff_dev/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pgierz/anaconda3/envs/nml_diff_dev/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/pgierz/anaconda3/envs/nml_diff_dev/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pgierz/anaconda3/envs/nml_diff_dev/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "fortran_progs.py", line 14, in compile_jsbach_init_file
    command_to_run = f"{config('fc')} lala.f90"
  File "/Users/pgierz/anaconda3/envs/nml_diff_dev/lib/python3.7/site-packages/everett/manager.py", line 632, in __call__
    '%s is not a valid key for this component' % (key,)
everett.InvalidKeyError: fc is not a valid key for this component


```

**Comment by willkg** [comment]
The `config` class member in `AppConfig` needs to be named `required_config` and then it should work. Here's a slimmed down and fixed version:

```python
from everett.component import RequiredConfigMixin, ConfigOptions
from everett.manager import ConfigOSEnv, ConfigManager
from everett.ext.yamlfile import ConfigYamlEnv


CONFIG_FILES = ["my.yaml"]


class AppConfig(RequiredConfigMixin):
    required_config = ConfigOptions()
    required_config.add_option(
        "debug", parser=bool, default="false", doc="Switch debug mode on and off."
    )
    required_config.add_option(
        "fc",
        default="gfortran",
        doc="Which ``FORTRAN`` compiler to use for the ``foo`` program",
        namespace="foo",
        parser=str,
    )


def get_config():
    environments = [
        ConfigOSEnv(),
        ConfigYamlEnv(CONFIG_FILES),
    ]
    manager = ConfigManager(
        environments=environments,
    )

    return manager.with_options(AppConfig())


config = get_config()
print(config('fc'))
```

Looking at the documentation for RequiredConfigMixin, it doesn't make this clear but the examples use `required_config`. I'll tweak the docs to make it explicit.

Hope that helps!

**Comment by pgierz** [comment]
Thanks! That solves it :-) I naively assumed it was just another variable without remembering that I'm inheriting a class, so obviously the name matters. The update in the docs which is now online is also very clear, and would have stopped me from just changing the name. However, might there be a way to catch the error and give end users a hint?

**Comment by willkg** [comment]
Currently, I think this is better handled in documentation. Otherwise if someone wanted to do something to work around `required_config`, they'd have a lot more to work around. We'll see if it comes up again.

Glad it helped!
