### ISSUE TITLE
Can't use YAML lists

### ISSUE THREAD

**Issue by pjz** [willkg/everett#98]
I tried to use a config file `config.yaml` like:
```
foo:
  - bar
  - baz
  - bal
```
with a small test program `testev.py`:
```
import os

from everett.manager import ConfigManager, ListOf
from everett.ext.yamlfile import ConfigYamlEnv

config = ConfigManager([
        ConfigYamlEnv([
                    os.environ.get('CONFIG_YAML'),
                ])
])

val = config('foo', parser=ListOf(str))
print(f"foo is {config('foo')}")
```
called like:
```
$ CONFIG_YAML=config.yaml ./bin/python testev.py 
```
and got:
```
Traceback (most recent call last):
  File "testev.py", line 9, in <module>
    os.environ.get('CONFIG_YAML'),
  File "/tmp/testev/lib/python3.7/site-packages/everett/ext/yamlfile.py", line 123, in __init__
    self.cfg = self.parse_yaml_file(path)
  File "/tmp/testev/lib/python3.7/site-packages/everett/ext/yamlfile.py", line 157, in parse_yaml_file
    return traverse([], data)
  File "/tmp/testev/lib/python3.7/site-packages/everett/ext/yamlfile.py", line 149, in traverse
    val, path
everett.ConfigurationError: Invalid value ['bar', 'baz', 'bal'] in file /tmp/testev/config.yaml: values must be double-quoted strings
```

The YAML is valid, but everett seems surprised to get a list instead of a string.

**Comment by willkg** [comment]
It's been over a year and no one has chimed in on this issue, so I'm going to close it out.
